### ISSUE TITLE
Isolating levels doesn't work correctly for the combined levels

### ISSUE THREAD

**Issue by dobrzhanskyi** [autodesk-tandem/tandem-sample-emb-viewer#10]
<img width="1228" alt="Screenshot 2024-04-04 at 15 05 50" src="https://github.com/autodesk-tandem/tandem-sample-emb-viewer/assets/33500265/b404d178-3824-430e-85a9-9f078e95ac57">

**Issue Description:**
The functionality to isolate levels by name encounters an error when attempting to isolate combined levels with a user-assigned name. The existing logic does not handle cases where multiple levels are combined and given a custom name.

**Steps to Reproduce:**

- Combine multiple levels in the Autodesk tandem.
- Assign a custom name to the combined level.
- Attempt to isolate the combined levels by their assigned name.
- Observe the error in isolation, as the existing logic only uses one level entry.

**Expected Behavior:**
The functionality to isolate levels by name should properly handle cases where multiple levels are combined and given a custom name. All combined levels associated with the specified name should be accurately isolated in the viewer.

**Additional Details:**

The current error affects the accuracy of level isolation and viewer display.
The proposed solution involves collecting all combined levels with the specified name into an array of level ids.
Each combined level's element IDs are concatenated for every model, enabling their accurate isolation in the viewer.
**Proposed Fix:**
To resolve this issue, the code logic should be updated to correctly handle combined levels with custom names. Consider implementing a solution that collects all combined levels into an array and concatenates their element IDs for accurate isolation in the viewer.

**Comment by liskaj** [comment]
Fixed
